version: "3.3"
services:
 db:
  image: mysql:5.7
  restart: always
  ports:
    - 9306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=db
  container_name: db
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 9081:80
  environment:
    - PMA_ARBITRARY=1
  container_name: phpmyadmin
 php:
  image: php:7.2-apache
  ports:
    - 9080:80
    - 9443:443
  user: root
  container_name: php
